services:
  kard:
    image: eclipse-temurin:11.0.20_8-jre-alpine
    container_name: kard
    hostname: kard
    command: "/opt/kard/bin/kard"
    networks:
      - kanet
    environment:
      - BOOTSTRAP_SERVERS=kafka-1:9092
      - SECURITY_SSL=yes
      - SSL_TRUSTSTORE_LOCATION=/opt/certs/kafka.truststore.jks
      - SSL_TRUSTSTORE_PASSWORD=askass
    volumes:
      - ./build/install/kard:/opt/kard
      - ../secrets/certs/kafka.truststore.jks:/opt/certs/kafka.truststore.jks

networks:
  kanet:
    external: true
    name: kassnet
