services:
  zookeeper:
    image: zookeeper
    container_name: zookeeper
    ports:
      - "2181"
    networks:
      - kanet

  kafka-1:
    image: wurstmeister/kafka
    container_name: kafka-1
    hostname: kafka-1
    expose:
      - 9092
    ports:
      - "19092:19092"
    networks:
      - kanet
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:19092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-1:9092,EXTERNAL://localhost:19092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

  kafka-2:
    image: wurstmeister/kafka
    container_name: kafka-2
    hostname: kafka-2
    expose:
      - 9092
    ports:
      - "29092:29092"
    networks:
      - kanet
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://:9092,EXTERNAL://:29092
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka-2:9092,EXTERNAL://localhost:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
    depends_on:
      - zookeeper

networks:
  kanet:
    name: kassnet
